apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "flypath.name" .}}
  labels:
{{ include "flypath.labels.standard" . | indent 4}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "flypath.app" . | indent 6}}
  template:
    metadata:
      labels:
{{ include "flypath.app" . | indent 8}}
    spec:
      containers:
        - name: flypath
          image: {{.Values.registry}}/flypath:{{.Chart.Version}}
          command:
            - flypath
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_NAME
              value: {{template "flypath.name" .}}
            - name: LOGGING_LEVEL
              value: {{.Values.loggingLevel  | quote }}
            - name: TRACING_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: METRICS_ADDR
              value: ":{{.Values.metricsPort}}"

{{ include "neohelperchart.lifecycle-definitions" . | indent 10 }}
          resources:
{{ toYaml .Values.resources | indent 14 }}
      affinity:
{{ include "neohelperchart.anti-affinity-definitions" . | indent 8 }}
