apiVersion: v1
kind: Service
metadata:
  name: {{ include "flypath.name" . }}
  labels:
{{ include "flypath.labels.standard" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metricsPort | quote }}
    prometheus.io/path: "/application/prometheus"
spec:
  ports:
    - name: http
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
{{ include "flypath.template.labels" . | indent 4 }}
  type: ClusterIP
